language: objective-c

os: osx

env:
  - PROJECT_DIR="$(pwd)/Ludum Dare 39/Ludum Dare 39" INSTALLER_HASH="5d30cf096e79" INSTALLER_VERSION="2017.1.1f1"

before_install:
  - chmod a+x ./Travis/*

install:
  - ./Travis/install.sh

script:
  - ./Travis/test.sh editmode
  - ./Travis/test.sh playmode
  - ./Travis/build.sh
  
cache:
  directories:
  - UnityInstallFileFolder