language: objective-c

os: osx

env:
  - PROJECT_DIR="$(pwd)/Ludum Dare 39/Ludum Dare 39" TEST_PLATFORM=editmode
  - PROJECT_DIR="$(pwd)/Ludum Dare 39/Ludum Dare 39" TEST_PLATFORM=playmode

before_install:
  - chmod a+x ./Travis/install.sh
  - chmod a+x ./Travis/test.sh

install:
  - ./Travis/install.sh

script:
  - ./Travis/test.sh